### PR TITLE
ds/#006 Tests

### PR DESCRIPTION
**Pull request by denstre**
Adds several tests

### CODE REVIEW

**Comment by denstre** [comment]
!test

**Comment by johanneshiry** [comment]
@denstre please let me know when this pr is ready for review

**Comment by denstre** [comment]
!test

**Comment by denstre** [comment]
!test

**Review by johanneshiry — CHANGES_REQUESTED** [review]
Code in general looks good - please resolve codacy issues (see [https://app.codacy.com/gh/ie3-institute/java-apexcharts/pullRequest?prid=4915669](https://app.codacy.com/gh/ie3-institute/java-apexcharts/pullRequest?prid=4915669)) - afterwards I'm willing to approve the PR

**Comment by johanneshiry** [comment]
!test

**Comment by denstre** [comment]
!test

**Comment by johanneshiry** [comment]
!test

**Pull request merged**
